insert into ordendeservicio(numeroorden,tipo) VALUES (2, 'TERAPIA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (3, 'HOSPITALIZACIÓN' );
insert into ordendeservicio(numeroorden,tipo) VALUES (4, 'PROCEDIMIENTO' );
insert into ordendeservicio(numeroorden,tipo) VALUES (5, 'ESPECIALISTA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (6, 'TERAPIA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (7, 'HOSPITALIZACIÓN' );
insert into ordendeservicio(numeroorden,tipo) VALUES (8, 'PROCEDIMIENTO' );
insert into ordendeservicio(numeroorden,tipo) VALUES (9, 'ESPECIALISTA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (10, 'TERAPIA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (11, 'HOSPITALIZACIÓN' );
insert into ordendeservicio(numeroorden,tipo) VALUES (12, 'PROCEDIMIENTO' );
insert into ordendeservicio(numeroorden,tipo) VALUES (13, 'ESPECIALISTA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (14, 'TERAPIA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (15, 'HOSPITALIZACIÓN' );
insert into ordendeservicio(numeroorden,tipo) VALUES (16, 'PROCEDIMIENTO' );
insert into ordendeservicio(numeroorden,tipo) VALUES (17, 'ESPECIALISTA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (18, 'TERAPIA' );
insert into ordendeservicio(numeroorden,tipo) VALUES (19, 'HOSPITALIZACIÓN' );
insert into ordendeservicio(numeroorden,tipo) VALUES (20, 'PROCEDIMIENTO' );
insert into ordendeservicio(numeroorden,tipo) VALUES (21, 'ESPECIALISTA' );



insert into medicamento(nombre, Empresa) VALUES ('paracetamol','Bayer');
insert into medicamento(nombre, Empresa) VALUES ('aspirina','Sanofi');
insert into medicamento(nombre, Empresa) VALUES ('omeprazol','J+J');
insert into medicamento(nombre, Empresa) VALUES ('Ramipril','Baxter');
insert into medicamento(nombre, Empresa) VALUES ('simvastatina','La Sante');
insert into medicamento(nombre, Empresa) VALUES ('Amlodipina','GSK');
insert into medicamento(nombre, Empresa) VALUES ('Atorvastatina','Bayer');
insert into medicamento(nombre, Empresa) VALUES ('Lansoprazol','Sanofi');
insert into medicamento(nombre, Empresa) VALUES ('colecalciferol','J+J');
insert into medicamento(nombre, Empresa) VALUES ('amoxicilina','Baxter');
insert into medicamento(nombre, Empresa) VALUES ('furosemida','La Sante');
insert into medicamento(nombre, Empresa) VALUES ('Co-codamol','GSK');


insert into receta(id, orden) VALUES ('123', 1);
insert into receta(id, orden) VALUES ('143', 1);
insert into receta(id, orden) VALUES ('125', 1);
insert into receta(id, orden) VALUES ('163', 5);
insert into receta(id, orden) VALUES ('223', 3);
insert into receta(id, orden) VALUES ('723', 6);
insert into receta(id, orden) VALUES ('923', 21);
insert into receta(id, orden) VALUES ('193', 14);
insert into receta(id, orden) VALUES ('120', 15);
insert into receta(id, orden) VALUES ('129', 17);
insert into receta(id, orden) VALUES ('623', 18);
insert into receta(id, orden) VALUES ('173', 13);
insert into receta(id, orden) VALUES ('343', 16);
insert into receta(id, orden) VALUES ('333', 11);
insert into receta(id, orden) VALUES ('283', 17);
insert into receta(id, orden) VALUES ('113', 18);
insert into receta(id, orden) VALUES ('191', 13);
insert into receta(id, orden) VALUES ('111', 7);
insert into receta(id, orden) VALUES ('222', 9);


insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'DELTUSS DP Nasal Decongestant Antihistamine CHERRY Flavor', 1);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Rimmel BB Cream Matte 9-IN-1 Skin Perfecting Super Makeup', 2);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Aesculus-Heel', 3);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Halibut', 4);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Lamotrigine', 5);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Neuro - Care', 6);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Pentoxifylline', 7);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Attention Plus', 8);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Gold Bond Ultimate Healing Concentrated Therapy', 9);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Gas Relief', 10);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Phenytoin Sodium', 11);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Night Magic', 12);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Old Spice High Endurance Clear', 13);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Monistat Complete Care Chafing Relief', 14);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Foam Safe', 15);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'TS (Talmostop) Talhwan', 16);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Rat Epithelium', 17);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Fentanyl', 18);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'SAFEWAY CARE', 19);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Flex24 Pain', 20);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('Colsanitas', 'Vinorelbine Tartrate', 21);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Lisinopril', 22);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Mixed Vespid hymenoptera venom Venomil Maintenance', 23);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Quinapril', 24);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Promethazine Hydrochloride', 25);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Harris Teeter', 26);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Estradiol', 27);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Regular Strength Acid Reducer', 28);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Fragaria Vitis Liver Support', 29);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'LAMOTRIGINE', 30);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'LANOXIN', 31);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'EXSEL SPORT', 32);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'CD DiorSnow White Reveal UV Shield Foundation 012-Porcelain', 33);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'HYDROXYZINE PAMOATE', 34);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Truvada', 35);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Salt Cedar', 36);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'TheraPlus', 37);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('COMPENSAR', 'Levisticum Quercus', 38);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Hyperactivity - Mental Focus', 39);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'TheraPlus', 40);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Tropicamide', 41);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Oxcarbazepine', 42);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Minipress', 43);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'donepezil hydrochloride', 44);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Softlips Pure Tint', 45);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Betamethasone Valerate', 46);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Ketoconazole', 47);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'severe sinus', 48);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Rizatriptan Benzoate', 49);
insert into EPS (NOMBRE, GERENTE, CDEPREVENCIO) values ('SURA', 'Digoxin', 50);



insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('1','Milos@gmail.com','Ricardo','Milos','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('2','maira@gmail.com','maira','perez','TARJETA DE IDENTIDAD','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('3','maria@gmail.com','maria','perez','CEDULA','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('4','Enrique@gmail.com','Enrique','perez','TARJETA DE IDENTIDAD','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('5','Jorge@gmail.com','Jorge','perez','CEDULA DE EXTRANJERIA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('6','Karen@gmail.com','Karen','perez','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('7','Cecilia@gmail.com','Cecilia','perez','CEDULA','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('8','Santiago@gmail.com','Santiago','perez','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('9','Daniel@gmail.com','Daniel','perez','CEDULA DE EXTRANJERIA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('10','Francisco@gmail.com','Francisco','perez','CEDULA','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('11','Antonio@gmail.com','Antonio','perez','CEDULA DE EXTRANJERIA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('12','Diana@gmail.com','Diana','perez','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('13','Michael@gmail.com','Michael','Jackson','CEDULA','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('14','Jose@gmail.com','Jose','perez','TARJETA DE IDENTIDAD','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('15','Jaime@gmail.com','Jaime','perez','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('16','Carlos@gmail.com','Carlos','perez','CEDULA','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('17','Carla@gmail.com','Carla','perez','TARJETA DE IDENTIDAD','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('18','Arturo@gmail.com','Arturo','perez','CEDULA','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('19','Marcela@gmail.com','Marcela','perez','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('20','Juliana@gmail.com','Juliana','perez','TARJETA DE IDENTIDAD','Colsanitas');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('21','Caro@gmail.com','Caro','perez','CEDULA','SURA');
insert into usuario(id, correo, nombre, apellido, tipoid, nombre_eps) values ('22','Felipe@gmail.com','Felipe','perez','CEDULA','Colsanitas');

insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Anette', 'Calypso', 'Berenice', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Sayre', 'Russell', 'Shelby', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Elvina', 'Novick', 'Ardelia', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Stevie', 'Glendale', 'Livvy', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Darin', 'Beilfuss', 'Katharyn', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Rich', 'Cherokee', 'Coralie', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Devlin', 'Melby', 'Jacqui', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Rowney', 'Birchwood', 'Noreen', 'Colsanitas');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Ekaterina', 'Commercial', 'Maressa', 'SURA');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Agnella', 'Fuller', 'Ulrike', 'SURA');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Kaela', 'Shasta', 'Enrica', 'SURA');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Dex', 'Corben', 'Robinett', 'SURA');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Inger', 'Union', 'Harmonia', 'SURA');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Neda', 'Ludington', 'Brandie', 'SURA');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Karney', 'Mandrake', 'Karoline', 'COMPENSAR');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Land', 'Alpine', 'Rici', 'COMPENSAR');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Uri', 'Delaware', 'Cathee', 'COMPENSAR');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Ilyse', 'Roth', 'Wilma', 'COMPENSAR');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Sibbie', '6th', 'Austine', 'COMPENSAR');
insert into IPS (NOMBRE, LOCALIZACION, RECEPCIONISTA, NOMBREEPS) values ('Min', 'Mcguire', 'Flori', 'COMPENSAR');



insert into medico(identificacion, registroMedico, NombreIPS) VALUES ('1','213123','Clínica Nueva');
insert into medico(identificacion, registroMedico, NombreIPS) VALUES ('2','213143','Clínica Chía');
insert into medico(identificacion, registroMedico, NombreIPS) VALUES ('3','213163','Laboratorio Ángela');
insert into medico(identificacion, registroMedico, NombreIPS) VALUES ('4','213187','Clínica El Country');

insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (1, 44, '6/12/2018', '22/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (2, 95, '22/11/2018', '3/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (3, 27, '18/2/2019', '13/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (4, 71, '2/9/2019', '16/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (5, 45, '29/5/2019', '18/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (6, 12, '4/10/2019', '10/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (7, 71, '22/7/2019', '10/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (8, 37, '17/1/2019', '2/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (9, 53, '8/12/2018', '30/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (10, 61, '7/10/2019', '26/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (11, 95, '5/12/2018', '8/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (12, 35, '31/10/2019', '10/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (13, 13, '3/5/2019', '31/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (14, 99, '17/8/2019', '17/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (15, 18, '9/6/2019', '28/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (16, 52, '21/12/2018', '21/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (17, 17, '23/2/2019', '30/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (18, 57, '12/7/2019', '5/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (19, 55, '18/4/2019', '1/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (20, 27, '29/8/2019', '27/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (21, 25, '2/11/2019', '9/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (22, 18, '28/8/2019', '11/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (23, 41, '8/10/2019', '13/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (24, 87, '27/10/2019', '14/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (25, 76, '26/6/2019', '8/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (26, 35, '5/1/2019', '20/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (27, 1, '26/3/2019', '14/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (28, 28, '13/3/2019', '31/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (29, 66, '20/10/2019', '24/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (30, 75, '27/11/2018', '14/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (31, 48, '30/8/2019', '1/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (32, 57, '30/10/2019', '18/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (33, 64, '7/11/2018', '16/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (34, 64, '24/4/2019', '13/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (35, 8, '25/1/2019', '5/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (36, 100, '27/5/2019', '10/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (37, 98, '5/4/2019', '7/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (38, 28, '20/7/2019', '27/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (39, 16, '6/3/2019', '22/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (40, 100, '14/12/2018', '1/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (41, 38, '29/9/2019', '1/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (42, 34, '19/2/2019', '19/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (43, 99, '17/7/2019', '3/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (44, 90, '1/11/2019', '9/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (45, 11, '24/5/2019', '1/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (46, 12, '19/7/2019', '29/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (47, 94, '31/5/2019', '14/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (48, 84, '10/4/2019', '16/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (49, 12, '6/10/2019', '10/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (50, 16, '1/12/2018', '31/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (51, 69, '8/5/2019', '12/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (52, 44, '31/8/2019', '4/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (53, 78, '5/2/2019', '14/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (54, 90, '7/1/2019', '13/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (55, 18, '1/11/2019', '12/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (56, 97, '31/7/2019', '14/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (57, 42, '30/3/2019', '9/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (58, 43, '22/12/2018', '19/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (59, 6, '19/4/2019', '31/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (60, 14, '26/9/2019', '21/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (61, 10, '10/6/2019', '20/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (62, 78, '25/6/2019', '15/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (63, 67, '26/3/2019', '29/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (64, 83, '5/7/2019', '5/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (65, 23, '12/5/2019', '14/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (66, 42, '11/4/2019', '3/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (67, 94, '4/2/2019', '1/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (68, 32, '20/2/2019', '14/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (69, 35, '11/4/2019', '9/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (70, 49, '7/10/2019', '14/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (71, 92, '22/7/2019', '26/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (72, 66, '16/11/2018', '6/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (73, 5, '10/12/2018', '17/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (74, 26, '27/1/2019', '13/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (75, 96, '22/3/2019', '21/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (76, 31, '22/6/2019', '8/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (77, 92, '26/10/2019', '21/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (78, 21, '3/11/2019', '25/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (79, 70, '19/1/2019', '1/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (80, 35, '27/12/2018', '13/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (81, 33, '30/7/2019', '28/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (82, 87, '11/4/2019', '5/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (83, 2, '29/4/2019', '15/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (84, 12, '4/4/2019', '6/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (85, 54, '19/10/2019', '6/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (86, 31, '3/9/2019', '23/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (87, 46, '25/5/2019', '23/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (88, 12, '22/7/2019', '3/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (89, 85, '17/6/2019', '20/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (90, 73, '14/4/2019', '5/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (91, 46, '18/10/2019', '12/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (92, 15, '4/3/2019', '14/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (93, 45, '17/2/2019', '5/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (94, 10, '7/1/2019', '29/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (95, 12, '6/2/2019', '10/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (96, 29, '26/1/2019', '14/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (97, 9, '22/9/2019', '10/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (98, 36, '14/8/2019', '27/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (99, 27, '16/8/2019', '14/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (100, 94, '21/2/2019', '25/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (101, 98, '27/3/2019', '1/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (102, 91, '29/11/2018', '8/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (103, 91, '28/2/2019', '19/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (104, 89, '17/3/2019', '10/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (105, 93, '13/9/2019', '11/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (106, 41, '13/5/2019', '5/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (107, 61, '21/12/2018', '6/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (108, 78, '28/4/2019', '7/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (109, 49, '28/12/2018', '26/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (110, 37, '25/12/2018', '5/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (111, 7, '3/2/2019', '4/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (112, 10, '22/3/2019', '31/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (113, 25, '25/7/2019', '10/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (114, 24, '1/5/2019', '1/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (115, 29, '31/8/2019', '9/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (116, 92, '20/11/2018', '25/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (117, 23, '6/6/2019', '30/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (118, 5, '8/10/2019', '9/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (119, 10, '11/4/2019', '29/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (120, 5, '21/11/2018', '14/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (121, 85, '17/6/2019', '30/4/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (122, 42, '6/4/2019', '24/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (123, 72, '17/1/2019', '17/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (124, 77, '31/7/2019', '9/8/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (125, 37, '28/11/2018', '16/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (126, 46, '2/6/2019', '24/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (127, 61, '2/4/2019', '15/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (128, 42, '3/4/2019', '3/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (129, 79, '7/4/2019', '20/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (130, 60, '19/8/2019', '25/1/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (131, 47, '16/11/2018', '12/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (132, 35, '1/6/2019', '24/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (133, 66, '2/11/2019', '29/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (134, 36, '18/1/2019', '8/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (135, 20, '3/5/2019', '12/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (136, 90, '30/7/2019', '17/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (137, 9, '16/6/2019', '6/6/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (138, 24, '13/6/2019', '15/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (139, 63, '29/11/2018', '11/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (140, 5, '27/12/2018', '7/2/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (141, 72, '5/10/2019', '5/5/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (142, 69, '13/8/2019', '30/3/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (143, 57, '30/10/2019', '6/7/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (144, 15, '3/9/2019', '9/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (145, 82, '23/6/2019', '20/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (146, 78, '28/11/2018', '23/11/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (147, 48, '8/10/2019', '29/12/2018');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (148, 18, '26/2/2019', '10/10/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (149, 99, '16/1/2019', '19/9/2019');
insert into CDEPREVENCION (ID, AFILIADOESPERADOS, FECHAFINAL, FECHAINICIAL) values (150, 15, '26/7/2019', '4/7/2019');
