--- Sentencias SQL para la creación del esquema de parranderos
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

-- USO
-- Copie el contenido de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada

-- Creación del secuenciador
create sequence epsandes_sequence;

-- Creaación de la tabla ORDENDESERVICIO y especificación de sus restricciones
CREATE TABLE ORDENDESERVICIO
   (NUMEROORDEN NUMBER, 
	TIPO VARCHAR2(255 BYTE), 
	CONSTRAINT ORDENDESERVICIO PRIMARY KEY (NUMEROORDEN))
    
    ;
	
ALTER TABLE ORDENDESERVICIO
	ADD CONSTRAINT CK_NUMORDEN_TIPO
    CHECK (TIPO IN ('ESPECIALISTA', 'TERAPIA', 'HOSPITALIZACIÓN', 'PROCEDIMIENTO'))
ENABLE;

-- Creaación de la tabla MEDICAMENTO y especificación de sus restricciones
CREATE TABLE MEDICAMENTO 
   (NOMBRE VARCHAR2(20 BYTE), 
	EMPRESA VARCHAR2(20 BYTE), 
	CONSTRAINT MEDICAMENTO PRIMARY KEY (NOMBRE));
	

-- Creaación de la tabla RECETA y especificación de sus restricciones
CREATE TABLE RECETA
   (ID VARCHAR2(20 BYTE), 
   ORDEN NUMBER, 
	CONSTRAINT RECETA PRIMARY KEY (ID));
	 
ALTER TABLE RECETA
	ADD CONSTRAINT FK_ORDENDESERVICIO_NUMEROORDEN 
	FOREIGN KEY (ORDEN)
    REFERENCES ORDENDESERVICIO(NUMEROORDEN)
ENABLE;

-- Creaación de la tabla EPS y especificación de sus restricciones
CREATE TABLE EPS
   (NOMBRE VARCHAR2(20 BYTE), 
	GERENTE VARCHAR2(255 BYTE),  
	CONSTRAINT EPS_PK PRIMARY KEY (NOMBRE));


-- Creaación de la tabla usuario y especificación de sus restricciones
CREATE TABLE USUARIO
(
  ID VARCHAR2(20 BYTE),
  CORREO VARCHAR2(20 BYTE),
  NOMBRE VARCHAR2(20 BYTE),
  APELLIDO VARCHAR2(20 BYTE),
  TIPOID VARCHAR2(20 BYTE),
  NOMBRE_EPS VARCHAR2(20 BYTE),
  CONSTRAINT USUARIO_PK PRIMARY KEY (ID));

ALTER TABLE USUARIO
ADD CONSTRAINT fk_U_EPS
    FOREIGN KEY (NOMBRE_EPS)
    REFERENCES EPS(NOMBRE)
ENABLE;
    
ALTER TABLE USUARIO
ADD CONSTRAINT Ck_U_TIPOID
    CHECK (TIPOID IN('CEDULA','TARJETA DE IDENTIDAD', 'CEDULA DE EXTRANJERIA')) 
ENABLE;

-- Creaación de la tabla IPS y especificación de sus restricciones
CREATE TABLE IPS 
(
  NOMBRE VARCHAR2(20 BYTE),
  LOCALIZACION VARCHAR2(20 BYTE),
  RECEPCIONISTA VARCHAR2(20 BYTE),
  NOMBREEPS VARCHAR2(20 BYTE),
  CONSTRAINT IPS_PK PRIMARY KEY (NOMBRE));

ALTER TABLE IPS
ADD CONSTRAINT fk_I_RECEPCIONISTA
    FOREIGN KEY (RECEPCIONISTA)
    REFERENCES USUARIO(id)
ENABLE;
    
ALTER TABLE IPS
ADD CONSTRAINT fk_I_NOMBREEPS
    FOREIGN KEY (NOMBREEPS)
    REFERENCES EPS(NOMBRE)
ENABLE;
    

-- Creaación de la tabla MEDICO y especificación de sus restricciones
CREATE TABLE MEDICO
(
  IDENTIFICACION VARCHAR2(20 BYTE),
  REGISTROMEDICO VARCHAR2(20 BYTE),
  NOMBRE_IPS VARCHAR2(20 BYTE), 
  CONSTRAINT MEDICO_PK PRIMARY KEY (IDENTIFICACION));

ALTER TABLE MEDICO
ADD CONSTRAINT fk_M_NOMBREIPS
    FOREIGN KEY (NOMBRE_IPS)
    REFERENCES IPS(NOMBRE)
ENABLE;
    
CREATE TABLE MEDICO_GENERAL
(
  NOMBRE VARCHAR2(20 BYTE),
  APELLIDO VARCHAR2(20 BYTE),
  IDENTIFICACION VARCHAR2(20 BYTE),
  CONSTRAINT MEDICOG_PK PRIMARY KEY (NOMBRE, APELLIDO));

ALTER TABLE MEDICO_GENERAL
ADD CONSTRAINT fk_MG_IDENTIFICACION
    FOREIGN KEY (IDENTIFICACION)
    REFERENCES MEDICO(IDENTIFICACION)
ENABLE;
    
CREATE TABLE MEDICO_ESPECIALISTA
(
  NOMBRE VARCHAR2(20 BYTE),
  APELLIDO VARCHAR2(20 BYTE),
  ESPECIALIDAD VARCHAR2(20 BYTE),
  IDENTIFICACION VARCHAR2(20 BYTE),
  CONSTRAINT MEDICOE_PK PRIMARY KEY (NOMBRE, APELLIDO));

ALTER TABLE MEDICO_ESPECIALISTA
ADD CONSTRAINT fk_ME_IDENTIFICACION
    FOREIGN KEY (IDENTIFICACION)
    REFERENCES MEDICO(IDENTIFICACION)
ENABLE;

CREATE TABLE AFILIADO
(
  ID VARCHAR2(20 BYTE),
  FECHA_NACIMIENTO DATE,
  ORDEN_DE_SERVICIO NUMBER,
  CONSTRAINT AFILIADO_PK PRIMARY KEY (ID));

ALTER TABLE AFILIADO
ADD CONSTRAINT fk_A_ID
    FOREIGN KEY (ID)
    REFERENCES USUARIO(ID)
ENABLE;

ALTER TABLE AFILIADO
ADD CONSTRAINT fk_A_ORDEN_DE_SERVICIO
    FOREIGN KEY (ORDEN_DE_SERVICIO)
    REFERENCES ORDENDESERVICIO(NUMEROORDEN)
ENABLE;


CREATE TABLE SERVICIO
(
  CODIGO_DE_SERVICIO NUMBER,
  HORARIO VARCHAR2(20 BYTE),
  CAPACIDAD NUMBER,
  NOMBRE_IPS VARCHAR2(20 BYTE),
  ORDEN_DE_SERVICIO NUMBER,
  ID_AFILIADO VARCHAR2(20 BYTE),
  CONSTRAINT SERVICIO_PK PRIMARY KEY (CODIGO_DE_SERVICIO));

ALTER TABLE SERVICIO
ADD CONSTRAINT fk_S_NOMBRE_IPS
    FOREIGN KEY (NOMBRE_IPS)
    REFERENCES IPS(NOMBRE)
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT fk_S_ODS
    FOREIGN KEY (ORDEN_DE_SERVICIO)
    REFERENCES ORDENDESERVICIO(NUMEROORDEN)
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT fk_S_IDA
    FOREIGN KEY (ID_AFILIADO)
    REFERENCES AFILIADO(ID)
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT Ck_S_CAPACIDAD
    CHECK (CAPACIDAD >0)
ENABLE;

CREATE TABLE RECETAN
(
  ID_RECETA VARCHAR2(20 BYTE),
  MEDICAMENTO VARCHAR2(20 BYTE),
  CONSTRAINT RECETAN_PK PRIMARY KEY (ID_RECETA, MEDICAMENTO));

ALTER TABLE RECETAN
ADD CONSTRAINT fk_R_IDR
    FOREIGN KEY (ID_RECETA)
    REFERENCES RECETA(ID)
ENABLE;

ALTER TABLE RECETAN
ADD CONSTRAINT fk_R_MEDICAMENTO
    FOREIGN KEY (MEDICAMENTO)
    REFERENCES MEDICAMENTO(NOMBRE)
ENABLE;

CREATE TABLE CONSULTA
(
  CODIGO_SERVICIO NUMBER,
  TIPO VARCHAR2(20 BYTE),
  TRIAGE VARCHAR2(255 BYTE),
  RECETA VARCHAR2(20 BYTE),
  CONSTRAINT CONSULTA_PK PRIMARY KEY (CODIGO_SERVICIO));

ALTER TABLE CONSULTA
ADD CONSTRAINT CK_C_TIPO 
	CHECK (TIPO IN ('CONTROL', 'URGENCIAS', 'GENERAL','ESPECIALISTA'))
ENABLE;

ALTER TABLE CONSULTA
ADD CONSTRAINT fk_C_CS
    FOREIGN KEY (CODIGO_SERVICIO)
    REFERENCES SERVICIO(CODIGO_DE_SERVICIO)
ENABLE;

ALTER TABLE CONSULTA
ADD CONSTRAINT fk_C_RECETA
    FOREIGN KEY (RECETA)
    REFERENCES RECETA(ID)
ENABLE;

COMMIT;